version: "3.8"

services:
  news-scraper-server:
    build: .
    depends_on:
      tengri-news-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_PASSWORD=0604
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tengri_news
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tengri-news-db/tengri_news
    networks:
      - kafka-network

  tengri-news-db:
    container_name: tengri-news-db
    image: postgres
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: 0604
      POSTGRES_USER: postgres
      POSTGRES_DB: tengri_news
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

networks:
  kafka-network:
    name: kafka_network
    external: true


